# Generated by Django 2.0.4 on 2018-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_exhibit'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='logoFileName',
            field=models.CharField(help_text='Enter logo file name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(help_text='Enter Exhbit Name', max_length=200),
        ),
    ]
